openapi: '3.0.0'
info:
  title: Inventory API
  description: >
    This API holds information on all of Dan's products that he can seel at his cafe.
    It also ensures that prices are configured based on special events and inventory status (too many, price goes down).

    As standard, customers will only be able to access APIs specifically for listing the available items and browsing
    what is available for the day. Other APIs are used for maintaining the inventory when items are sold or updated.
  version: 0.0.1

paths:
  '/v1/product':
    post:
      requestBody:
        content:
          application/json:
            schema:
              '$ref': '#/components/requestBodies/ProductBody'
      responses:
        '201':
          description: Create a new product
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Product'
  '/v1/product/{id}':
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: int
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                '$ref': '#/components/responses/Product'
  '/v1/product/{id}/price':
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: integer
      responses:
        '200':
          description: >
            Found the prices
          content:
            application/json:
              schema:
                '$ref': '#/components/responses/ProductPrices'

  '/v1/product/{id}/inventory':
    get:
      description: |
        Return the inventory details for the given product
      responses:
        '200':
          description: Successful lookup
          content:
            'application/json':
               schema:
                 $ref: '#/components/responses/ProductInventory'

components:
  schemas:
    Product:
      type: object
      properties:
        display_name:
          type: string
        description:
          type: string
        labels:
          type: array
          items:
            type: string
    Inventory:
      type: object
      properties:
        product_id:
          type: integer
        count:
          type: integer
        last_ordered:
          type: string
          format: 'date-time'
        request_time:
          type: string
          format: 'date-time'
    Price:
      type: object
      properties:
        price_date:
          type: string
          format: 'date-time'
        price:
          type: float
    ProductPrices:
      type: object
      properties:
        product_id:
          type: integer
        prices:
          type: array
          items:
            $ref: '#/components/schemas/Price'
  requestBodies:
    ProductBody:
      description: >
        the request body for a Product when creating
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
  responses:
    Product:
      description: >
        Basic Product Response
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Product'
              - type: object
                properties:
                  product_id:
                    type: integer
    ProductInventory:
      description: >
        Describes the current inventory status of the given product
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Inventory'
    ProductPrices:
      description: >
        Current prices of the requet product
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductPrices'
